name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Get modules
      run: go install github.com/dyatlov/go-opengraph/opengraph

    - name: Build
      run: go build -v ./cmd/server/main.go

    - name: Test
      run: go test -v ./...
